export interface Movie {
    Title: string,
    Released: string,
    Runtime: string,
    Year: string,
    imdbRating: string,
    imdbVotes: string,
    Rated: string,
    Plot: string,
    Metascore: string,
    Country: string,
    BoxOffice: string,
    Actors: string,
    Poster: string,
    imdbID: string,
    Director: string,
    Language: string,
    Genre: string,
}